# config.py
QDRANT_URL = "http://localhost:6333"
COLLECTION_NAME = "hytale_codebase"
EMBEDDING_MODEL_NAME = "mixedbread-ai/mxbai-embed-large-v1"

RETRIEVAL_FIRST_TOP_K = 30
RETRIEVAL_USUAL_TOP_K = 30

LLM_ENVIRONMENT_KEY_NAME="XAI_API_KEY"
LLM_BASE_URL = "https://api.x.ai/v1"
LLM_MODEL = "grok-4-1-fast-reasoning"
LLM_TEMPERATURE = 0.2
FALLBACK_LLM_ENVIRONMENT_KEY_NAME="OPENAI_API_KEY"
FALLBACK_LLM_BASE_URL = "https://api.openai.com/v1"
FALLBACK_LLM_MODEL = "gpt-5-mini"  
FALLBACK_LLM_TEMPERATURE = 1.0

DISCORD_COMMAND_PREFIX = "!"
MAX_HISTORY_MESSAGES = 12
HISTORY_KEEP_LAST = 8
MESSAGE_CHUNK_LIMIT = 1800

METRICS_FILE = "data/usage_metrics.jsonl"
