import os

QDRANT_URL = os.getenv("QDRANT_URL")
COLLECTION_NAME = "hytale_codebase"
EMBEDDING_MODEL_NAME = "mixedbread-ai/mxbai-embed-large-v1"

RETRIEVAL_FIRST_TOP_K = 30
RETRIEVAL_USUAL_TOP_K = 30

LLM_ENVIRONMENT_KEY_NAME="LITELLM_MASTER_KEY"
LLM_BASE_URL = os.getenv("LITELLM_API_BASE")
LLM_MODEL = "grok-4-1-fast-reasoning"

DISCORD_COMMAND_PREFIX = "!"
MAX_HISTORY_MESSAGES = 12
HISTORY_KEEP_LAST = 8
MESSAGE_CHUNK_LIMIT = 1800

METRICS_FILE = "data/usage_metrics.jsonl"
